import type { Metadata } from "next";
import { Georama, Roboto, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const georama = Georama({
  variable: "--font-georama",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${georama.variable} ${roboto.variable} ${inter.variable} antialiased`}
      >
        <main>
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
